version: "3.8"

services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    networks:
      - internal

  express_server:
    volumes:
      - .:/app:z
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - internal

volumes:
  db:

networks:
  internal:
    external: false
    driver: bridge
